baseURL = "https://lab.hackeradam.com/"
languageCode = "en-us"
title = "Adam Thompson's Lab Notebook"
theme = "etch"

[params]
    description = "Adam Thompson's public lab notes."
    copyright = "Copyright  2021, Adam Thompson."
    dark = "auto"
    highlight = "true"

[meu]
    [[menu.main]]
        identifier = "posts"
        name = "posts"
        title = "posts"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "about"
        url = "/about"
        weight = 2
    [[menu.main]]
        identifier = "Main Site"
        name = "Main Site"
        title = "Main Site"
        url = "https://hackeradam.com"
        weight = 3

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true